spring:
  application:
    name: priceflow

  datasource:
    url: jdbc:postgresql://ep-lively-snow-an5kl8vn-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_G4JFzKeE0Rsw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
